version: "3"
services: # An example. You can modify such as defining more than one node for each type below.
    nginx: # webserver
        image: nginx:1.17
        container_name: paddict_nginx
        ports:
            - "8000:8000"
        volumes:
            - ./:/src
            - ./config/nginx:/etc/nginx/conf.d
            - ./static:/static
        depends_on:
            - web
        networks:
            - net

    db: # MySQL
        image: mariadb:5.5
        command: --bind-address=0.0.0.0
        container_name: paddict_db
        environment:
            - MYSQL_HOST=localhost
            - MYSQL_PORT=3306  # cannot change this port to other number
            - MYSQL_ROOT_HOST=%
            - MYSQL_DATABASE=paddict
            - MYSQL_ROOT_PASSWORD=paddict
        ports:
            - "33061:3306"
        volumes:
            - ./db/mariadb:/var/lib/mysql
        networks:
            - net

    neo4j: # Graph data indexing
        image: neo4j:3.0
        container_name: paddict_neo4j
        ports:
            - 7474:7474
            - 7687:7687
        volumes:
            - ./db/neo4j:/data/dbms
        environment:
            NEO4J_AUTH: 'neo4j/paddict'
        networks:
            - net

    redis: # key-value DB for async tasks
        image: redis:5.0.5
        container_name: paddict_redis
        networks:
            - net
    
    es01:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
        container_name: es01
        environment:
            - node.name=es01
            - discovery.seed_hosts=es02
            - cluster.initial_master_nodes=es01,es02
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - esdata01:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        networks:
            - net
  
    es02:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
        container_name: es02
        environment:
            - node.name=es02
            - discovery.seed_hosts=es01
            - cluster.initial_master_nodes=es01,es02
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - esdata02:/usr/share/elasticsearch/data
        networks:
            - net
    web:
        build: .
        depends_on:
            - db
            - neo4j
            - redis
            - es01
            - es02
        volumes:
            - ./:/src
            - ./static:/static
        container_name: paddict_main
        expose:
            - "8000"
        command: 
            - bash 
            - -c 
            - |
                /etc/init.d/mysql start 
                python manage.py collectstatic --noinput 
                python manage.py makemigrations 
                python manage.py migrate 
                python manage.py install_labels
                gunicorn papers.wsgi -b 0.0.0.0:8000
        networks:
            - net

    supervisor: # we need this node to do some others stuffs such as CERMINE/OCR/download, .etc. A human user will login to here to perform some supervised tasks manually. Logs are recorded by docker.
        build: .
        depends_on:
            - web
        volumes:
            - ./:/src
            - ./static:/static
        container_name: paddict_supervisor
        stdin_open: true # must have this to prevent stopping after up
        tty: true # must have this
        networks:
            - net
        #command:
            #- /etc/init.d/mysql start
            #- apt install -y openjdk-8-jdk
            #- java -version

volumes:
    esdata01:
        driver: local
    esdata02:
        driver: local

networks:
    net:
        driver: bridge
