# Generated by Django 2.2.2 on 2019-06-21 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=4096)),
                ('pdf_link', models.CharField(max_length=4096)),
                ('abstract', models.CharField(blank=True, max_length=20000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(to='crawler.Author')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Supp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_link', models.CharField(max_length=4096)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.Document')),
            ],
            options={
                'ordering': ('pdf_link',),
            },
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['name'], name='name'),
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('name',)},
        ),
        migrations.AddIndex(
            model_name='supp',
            index=models.Index(fields=['pdf_link'], name='link'),
        ),
        migrations.AlterUniqueTogether(
            name='supp',
            unique_together={('pdf_link',)},
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['title'], name='title'),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('title',)},
        ),
    ]
