# Generated by Django 2.2.2 on 2019-06-21 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='The IEEE Conference on Computer Vision and Pattern Recognition (CVPR)', max_length=2048)),
                ('shortname', models.CharField(default='CVPR', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('shortname',),
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['name'], name='eventname'),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('name',)},
        ),
        migrations.AddField(
            model_name='document',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crawler.Event'),
        ),
    ]
