# Generated by Django 2.2.2 on 2019-06-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_auto_20190621_1118'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='eventname',
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['name', 'shortname'], name='eventname'),
        ),
    ]
