# Generated by Django 2.2.2 on 2019-06-21 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_auto_20190621_1121'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='supp',
            name='link',
        ),
        migrations.AlterUniqueTogether(
            name='supp',
            unique_together=set(),
        ),
    ]
