# Generated by Django 2.2.2 on 2019-06-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_auto_20190621_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='centred',
            field=models.BooleanField(default=False),
        ),
    ]
