# Generated by Django 2.2.2 on 2019-06-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0007_tag_tagassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='words',
            field=models.TextField(default=''),
        ),
    ]
