# Generated by Django 2.2.2 on 2019-06-23 10:47

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0008_document_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='notes',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
