# Generated by Django 2.2.2 on 2019-06-24 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0010_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set(),
        ),
    ]
